name: 'GitEvents Broadcast'
description: 'Broadcast events to Discord, Bluesky, Mailchimp, Meetup, and Luma'
author: 'GitEvents'
branding:
  icon: 'radio'
  color: 'blue'
runs:
  main: dist/index.js
  using: node20
