name: Post an Event on Bluesky

on:
  workflow_call:
    inputs:
      post:
        type: string
        required: true
    secrets:
      BSKY_IDENTIFIER:
        required: true
      BSKY_PASSWORD:
        required: true

jobs:
  bluesky:
    runs-on: ubuntu-latest
    steps:
      - uses: zentered/bluesky-post-action@v0.0.2
        with:
          post: ${{ inputs.post }}
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
