name: Integraton Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: End to End Test
        uses: ./
        env:
          EVENTBRITE_API_KEY: ${{ secrets.EVENTBRITE_API_KEY }}
          EVENTBRITE_ORG_ID: ${{ secrets.EVENTBRITE_ORG_ID }}
        with:
          enable-eventbrite: true
