name: Tween an Event on Twitter

on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true
    secrets:
      consumer-key:
        required: true 
      consumer-secret: 
        required: true
      access-token:
        required: true
      access-token-secret:
        required: true

jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ inputs.status }}
          consumer-key: ${{ secrets.consumer-key }}
          consumer-secret: ${{ secrets.consumer-secret }}
          access-token: ${{ secrets.access-token }}
          access-token-secret: ${{ secrets.access-token-secret }}